### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Iskander54** [fergarrui/ethereum-graph-debugger#16]
Hey ! I try to use your debugger but it is not working, 
I tried both with and without the docker but it raises the same issues : 

What should I do ? 

``
debugger_1  | ERROR in ./src/client/components/Version/Version.js
debugger_1  | Module not found: Error: Can't resolve '../../_redux/actions' in '/opt/app/src/client/components/Version'
debugger_1  |  @ ./src/client/components/Version/Version.js 16:38-69
debugger_1  |  @ ./src/client/components/TopNavBar/TopNavBar.js
debugger_1  |  @ ./src/client/App.js
debugger_1  |  @ ./src/index.js
debugger_1  | 
debugger_1  | ERROR in ./src/client/components/Graph/Graph.js
debugger_1  | Module not found: Error: Can't resolve '../../_redux/actions.js' in '/opt/app/src/client/components/Graph'
debugger_1  |  @ ./src/client/components/Graph/Graph.js 32:38-72
debugger_1  |  @ ./src/client/components/TransactionDebugger/TransactionDebugger.js
debugger_1  |  @ ./src/client/components/Panel/Panel.js
debugger_1  |  @ ./src/client/components/Main/Main.js
debugger_1  |  @ ./src/client/App.js
debugger_1  |  @ ./src/index.js
debugger_1  | 
debugger_1  | ERROR in ./src/client/components/Main/Main.js
debugger_1  | Module not found: Error: Can't resolve '../../_redux/actions.js' in '/opt/app/src/client/components/Main'
debugger_1  |  @ ./src/client/components/Main/Main.js 34:38-72
debugger_1  |  @ ./src/client/App.js
debugger_1  |  @ ./src/index.js
debugger_1  | 
debugger_1  | ERROR in ./src/client/components/MessageComp/MessageComp.js
debugger_1  | Module not found: Error: Can't resolve '../../_redux/actions.js' in '/opt/app/src/client/components/MessageComp'
debugger_1  |  @ ./src/client/components/MessageComp/MessageComp.js 28:38-72
debugger_1  |  @ ./src/client/App.js
debugger_1  |  @ ./src/index.js
debugger_1  | 
debugger_1  | ERROR in ./src/client/App.js
debugger_1  | Module not found: Error: Can't resolve './_redux/actions.js' in '/opt/app/src/client'
debugger_1  |  @ ./src/client/App.js 30:38-68
debugger_1  |  @ ./src/index.js
debugger_1  | 
debugger_1  | ERROR in ./src/index.js
debugger_1  | Module not found: Error: Can't resolve './client/_redux/store.js' in '/opt/app/src'
debugger_1  |  @ ./src/index.js 13:36-71
debugger_1  | npm ERR! code ELIFECYCLE
debugger_1  | npm ERR! errno 2
debugger_1  | npm ERR! ethereum-graph-debugger@3.6.0 webpack:prod: `webpack --mode production`
debugger_1  | npm ERR! Exit status 2
debugger_1  | npm ERR! 
debugger_1  | npm ERR! Failed at the ethereum-graph-debugger@3.6.0 webpack:prod script.
debugger_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debugger_1  | 
debugger_1  | npm ERR! A complete log of this run can be found in:
debugger_1  | npm ERR!     /root/.npm/_logs/2020-02-18T15_07_38_674Z-debug.log
debugger_1  | ERROR: "webpack:prod" exited with 2.
debugger_1  | npm ERR! code ELIFECYCLE
debugger_1  | npm ERR! errno 1
debugger_1  | npm ERR! ethereum-graph-debugger@3.6.0 build: `$(npm bin)/npm-run-all -s routes-gen tsc copy-index webpack:prod`
debugger_1  | npm ERR! Exit status 1
debugger_1  | npm ERR! 
debugger_1  | npm ERR! Failed at the ethereum-graph-debugger@3.6.0 build script.
debugger_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debugger_1  | 
debugger_1  | npm ERR! A complete log of this run can be found in:
debugger_1  | npm ERR!     /root/.npm/_logs/2020-02-18T15_07_38_796Z-debug.log
debugger_1  | ERROR: "build" exited with 1.
debugger_1  | npm ERR! code ELIFECYCLE
debugger_1  | npm ERR! errno 1
debugger_1  | npm ERR! ethereum-graph-debugger@3.6.0 start: `$(npm bin)/npm-run-all -s clean build start:simple`
debugger_1  | npm ERR! Exit status 1
debugger_1  | npm ERR! 
debugger_1  | npm ERR! Failed at the ethereum-graph-debugger@3.6.0 start script.
debugger_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debugger_1  | 
debugger_1  | npm ERR! A complete log of this run can be found in:``

**Comment by fergarrui** [comment]
Hi @Iskander54 , sorry for the late reply.
Please use the latest release version (https://github.com/fergarrui/ethereum-graph-debugger/releases/tag/v3.6.0), master can be unstable.

Thank you
