### ISSUE TITLE
Getting issue while trying to load smart contract.

### ISSUE THREAD

**Issue by bansatya** [fergarrui/ethereum-graph-debugger#2]
Application started successfully.However while provided the smart contract path and submit, it showed below error (in step 2)
Step 1: ![image](https://user-images.githubusercontent.com/33546557/57235240-f80f0680-7011-11e9-9719-e376c823d64e.png)

Step 2: ![image](https://user-images.githubusercontent.com/33546557/57235032-82a33600-7011-11e9-9fe6-e23cdd6f61a0.png)

**Comment by fergarrui** [comment]
Hi, 
I still didn't start with Windows support. I'm going to have a look, this was tested in Linux & MacOS only for now.

Thanks for reporting it

**Comment by bansatya** [comment]
@fergarrui , Thanks for your response.
The app is hosted in Linux(Ubuntu) platform. However, I am accessing it from windows browser.

**Comment by fergarrui** [comment]
@bansatya At the moment, it has to be run in the system where your contracts are. If you have the app hosted in a different platform, the path that you are entering in the first text input needs to exist where the app is running.
Basically the app reads the provided path and searches for contracts there.
At the moment this debugger is like a desktop app that runs in a browser, so you cannot host it in a different computer (unless you move your contracts to the host)

**Comment by fergarrui** [comment]
Closing the issue for inactivity
